language: go

go:
    - 1.5
    - 1.6
    - 1.7

git:
    depth: 1

sudo: required

install:
    - export GO15VENDOREXPERIMENT=1
    - go get -v -d

script:
    - make && make test

after_success:
    - echo $TRAVIS_GO_VERSION
    - if [ ! -z $TRAVIS_TAG ] && [ $TRAVIS_GO_VERSION == "1.7" ];
      then echo $UPX_CONFIG > $HOME/.upx.cfg && make upload VER=$TRAVIS_TAG;
      fi
