language: go

go:
    - "1.10"
    - "1.11"
    - "1.12"

git:
    depth: 1

sudo: required

install:
    - export GO15VENDOREXPERIMENT=1
    - sudo apt-get update && sudo apt-get install -y dnsutils
    - dig v0.api.upyun.com

script:
    - make app && make test

after_success:
    - echo $TRAVIS_GO_VERSION
    - if [ ! -z $TRAVIS_TAG ] && [ $TRAVIS_GO_VERSION == "1.12" ];
      then echo $UPX_CONFIG > $HOME/.upx.cfg && make upload VER=$TRAVIS_TAG;
      fi
